/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./index.html', './src/**/*.{vue,js,ts}'],
  darkMode: 'class',
  theme: {
    borderRadius: {
      none: '0',
      xs: '0.25rem',
      sm: '0.5rem',
      md: '1rem',
      lg: '1.5rem',
      full: '9999px',
    },
    screens: {
      sm: '600px',
      md: '870px',
      lg: '1024px',
      xl: '1440px',
    },
    colors: {
      transparent: 'transparent',
      primary: {
        50: 'rgb(var(--app-primary-50) / <alpha-value>)',
        100: 'rgb(var(--app-primary-100) / <alpha-value>)',
        300: 'rgb(var(--app-primary-300) / <alpha-value>)',
        200: 'rgb(var(--app-primary-200) / <alpha-value>)',
        400: 'rgb(var(--app-primary-400) / <alpha-value>)',
        500: 'rgb(var(--app-primary-500) / <alpha-value>)',
        600: 'rgb(var(--app-primary-600) / <alpha-value>)',
        700: 'rgb(var(--app-primary-700) / <alpha-value>)',
        800: 'rgb(var(--app-primary-800) / <alpha-value>)',
        900: 'rgb(var(--app-primary-900) / <alpha-value>)',
        A100: 'rgb(var(--app-primary-A100) / <alpha-value>)',
        A200: 'rgb(var(--app-primary-A200) / <alpha-value>)',
        A400: 'rgb(var(--app-primary-A400) / <alpha-value>)',
        A700: 'rgb(var(--app-primary-A700) / <alpha-value>)',
        contrast: {
          50: 'rgb(var(--app-primary-contrast-50) / <alpha-value>)',
          100: 'rgb(var(--app-primary-contrast-100) / <alpha-value>)',
          200: 'rgb(var(--app-primary-contrast-200) / <alpha-value>)',
          300: 'rgb(var(--app-primary-contrast-300) / <alpha-value>)',
          400: 'rgb(var(--app-primary-contrast-400) / <alpha-value>)',
          500: 'rgb(var(--app-primary-contrast-500) / <alpha-value>)',
          600: 'rgb(var(--app-primary-contrast-600) / <alpha-value>)',
          700: 'rgb(var(--app-primary-contrast-700) / <alpha-value>)',
          800: 'rgb(var(--app-primary-contrast-800) / <alpha-value>)',
          900: 'rgb(var(--app-primary-contrast-900) / <alpha-value>)',
          A100: 'rgb(var(--app-primary-contrast-A100) / <alpha-value>)',
          A200: 'rgb(var(--app-primary-contrast-A200) / <alpha-value>)',
          A400: 'rgb(var(--app-primary-contrast-A400) / <alpha-value>)',
          A700: 'rgb(var(--app-primary-contrast-A700) / <alpha-value>)',
        },
      },
      secondary: {
        50: 'rgb(var(--app-secondary-50) / <alpha-value>)',
        100: 'rgb(var(--app-secondary-100) / <alpha-value>)',
        200: 'rgb(var(--app-secondary-200) / <alpha-value>)',
        300: 'rgb(var(--app-secondary-300) / <alpha-value>)',
        400: 'rgb(var(--app-secondary-400) / <alpha-value>)',
        500: 'rgb(var(--app-secondary-500) / <alpha-value>)',
        600: 'rgb(var(--app-secondary-600) / <alpha-value>)',
        700: 'rgb(var(--app-secondary-700) / <alpha-value>)',
        800: 'rgb(var(--app-secondary-800) / <alpha-value>)',
        900: 'rgb(var(--app-secondary-900) / <alpha-value>)',
        A100: 'rgb(var(--app-secondary-A100) / <alpha-value>)',
        A200: 'rgb(var(--app-secondary-A200) / <alpha-value>)',
        A400: 'rgb(var(--app-secondary-A400) / <alpha-value>)',
        A700: 'rgb(var(--app-secondary-A700) / <alpha-value>)',
        contrast: {
          50: 'rgb(var(--app-secondary-contrast-50) / <alpha-value>)',
          100: 'rgb(var(--app-secondary-contrast-100) / <alpha-value>)',
          200: 'rgb(var(--app-secondary-contrast-200) / <alpha-value>)',
          300: 'rgb(var(--app-secondary-contrast-300) / <alpha-value>)',
          400: 'rgb(var(--app-secondary-contrast-400) / <alpha-value>)',
          500: 'rgb(var(--app-secondary-contrast-500) / <alpha-value>)',
          600: 'rgb(var(--app-secondary-contrast-600) / <alpha-value>)',
          700: 'rgb(var(--app-secondary-contrast-700) / <alpha-value>)',
          800: 'rgb(var(--app-secondary-contrast-800) / <alpha-value>)',
          900: 'rgb(var(--app-secondary-contrast-900) / <alpha-value>)',
          A100: 'rgb(var(--app-secondary-contrast-A100) / <alpha-value>)',
          A200: 'rgb(var(--app-secondary-contrast-A200) / <alpha-value>)',
          A400: 'rgb(var(--app-secondary-contrast-A400) / <alpha-value>)',
          A700: 'rgb(var(--app-secondary-contrast-A700) / <alpha-value>)',
        },
      },
      semantic: {
        50: 'rgb(var(--app-semantic-50) / <alpha-value>)',
        100: 'rgb(var(--app-semantic-100) / <alpha-value>)',
        300: 'rgb(var(--app-semantic-300) / <alpha-value>)',
        200: 'rgb(var(--app-semantic-200) / <alpha-value>)',
        400: 'rgb(var(--app-semantic-400) / <alpha-value>)',
        500: 'rgb(var(--app-semantic-500) / <alpha-value>)',
        600: 'rgb(var(--app-semantic-600) / <alpha-value>)',
        700: 'rgb(var(--app-semantic-700) / <alpha-value>)',
        800: 'rgb(var(--app-semantic-800) / <alpha-value>)',
        900: 'rgb(var(--app-semantic-900) / <alpha-value>)',
        A100: 'rgb(var(--app-semantic-A100) / <alpha-value>)',
        A200: 'rgb(var(--app-semantic-A200) / <alpha-value>)',
        A400: 'rgb(var(--app-semantic-A400) / <alpha-value>)',
        A700: 'rgb(var(--app-semantic-A700) / <alpha-value>)',
        contrast: {
          50: 'rgb(var(--app-semantic-contrast-50) / <alpha-value>)',
          100: 'rgb(var(--app-semantic-contrast-100) / <alpha-value>)',
          200: 'rgb(var(--app-semantic-contrast-200) / <alpha-value>)',
          300: 'rgb(var(--app-semantic-contrast-300) / <alpha-value>)',
          400: 'rgb(var(--app-semantic-contrast-400) / <alpha-value>)',
          500: 'rgb(var(--app-semantic-contrast-500) / <alpha-value>)',
          600: 'rgb(var(--app-semantic-contrast-600) / <alpha-value>)',
          700: 'rgb(var(--app-semantic-contrast-700) / <alpha-value>)',
          800: 'rgb(var(--app-semantic-contrast-800) / <alpha-value>)',
          900: 'rgb(var(--app-semantic-contrast-900) / <alpha-value>)',
          A100: 'rgb(var(--app-semantic-contrast-A100) / <alpha-value>)',
          A200: 'rgb(var(--app-semantic-contrast-A200) / <alpha-value>)',
          A400: 'rgb(var(--app-semantic-contrast-A400) / <alpha-value>)',
          A700: 'rgb(var(--app-semantic-contrast-A700) / <alpha-value>)',
        },
      },
    },
    extends: {},
  },
};
